server:
  port: 8080

spring:
  application:
    name: flyway-test
  config:
    import: optional:file:.env.development[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 1
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  output:
    ansi:
      enabled: ALWAYS
